[package]
name = "fpa-specr"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"  # by std::ffi
authors = ["Kentaro Tatsumi <paqira.2019@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/paqira/fpa-specr"
description = "Floating point number arithmetics and sqrt with specified rounding mode"
keywords = ["floating-point", "rounding-mode"]
readme = "README.md"
exclude = [".*"]
categories = ["mathematics", "science"]

[build-dependencies]
cc = { version = "1" }

[features]
f16 = []
f128 = []
