#[cfg(feature = "f128-softfloat")]
pub(crate) mod f128;
#[cfg(feature = "f16-softfloat")]
pub(crate) mod f16;
#[cfg(feature = "f32-softfloat")]
pub(crate) mod f32;
#[cfg(feature = "f64-softfloat")]
pub(crate) mod f64;
pub(crate) mod rounding_mode;
