name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fmt-clippy-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.64
        with:
          components: clippy, rustfmt
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy
      - name: Build
        run: cargo build
  vanilla:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo +nightly test
  fma:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C target-feature=+fma
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo +nightly test
