name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CFLAGS: -std=c11 -frounding-math
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.64
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
  fmt-clippy:
    runs-on: ubuntu-latest
    env:
      CFLAGS: -std=c11 -frounding-math
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo +nightly clippy
  hardfloat-f32-f64:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C target-cpu=native
#      use hardware fma
      CFLAGS: -std=c11 -frounding-math -mfma -march=native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo +nightly test --release
  softfloat:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C target-cpu=native
      CFLAGS: -std=c11 -frounding-math -mfma -march=native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo +nightly test --release -F softfloat -F f16-softfloat -F f128-softfloat
